### ISSUE TITLE
Enable Github pages so project looks more lively.

### ISSUE THREAD

**Issue by Abhey** [vitaliaventel/hacktoberfest2017#33]

**Comment by vitaliaventel** [comment]
@Abhey Hello, I can't understand, can you provide more information?
thanks for feedback.

**Comment by Abhey** [comment]
Enable github pages for this repository. Github pages are excellent way to host websites. For this project after enabling Github pages all the content of README.md file will be rendered and will be displayed in a more lively way. In Github pages you can also select from a wide range of themes. I have enabled those for my repository you can take a look at my final webpage http://www.abheyrana.me/hacktoberfest2017/ . To enable Github pages for your repository go to settings of your repository there you will find an option to enable those. Also please add the final link to the github web page in the description of your repository. 
PS. I know this is not a feature but still It will make your project more lively.

**Comment by vitaliaventel** [comment]
@Abhey thank you for help. I will make this project more interactive.
